export const initialState = {
    images: [],
    quality: 85,
    processing: false,
    aspectRatio: null,
    fileList: [],
    clearDialogOpen: false,
    dimensionError: false,
    fileSizeError: false,
    maintainAspectRatio: true,
    originalWidth: null,
    originalHeight: null,
    newWidthValue: "",
    newHeightValue: "",
    lastChanged: null,
    manualChange: false,
    invalidFilesDialogOpen: false,
    invalidFileNames: [],
    validTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/tiff'],
};
